### PR TITLE
Added getActiveProgram method

### PR DESCRIPTION
**Pull request by mcgordonite**
This is required to fix [KSRTE-268](https://jira.arm.com/browse/KSRTE-268).

When the user's machine goes to sleep, the plugin host is stopped. When it wakes up, a new plugin host instance is started. This means the active program retrieved via the `activeProgramChangeHandler` is not available, so RTE is never restarted.

With this change, it is possible to load the initial active program when the plugin host is started, and kick off RTE is there is one.

### CODE REVIEW

**Comment by mcgordonite** [comment]
This interface is used in https://github.com/ARMmbed/mbs-ide/pull/1745.

**Comment by thegecko** [comment]
Is it possible to fix this in Keil Studio by calling `activeProgramChangeHandler` function after the system resumes?

I'd rather not have 2 ways of getting the program if possible.

**Comment by mcgordonite** [comment]
Good question. I'm not sure we have an easily accessible event there, but I'll check.

Otherwise, we could probably wire it up so the handler passed to `activeProgramChangeHandler` is called immediately. It might be an odd architecture though - the "change" handler would be called when there was no real change in the value.

**Comment by mcgordonite** [comment]
Closing for now, hopefully this won't be needed.

**Comment by thegecko** [comment]
Thanks Matt

**Pull request closed without merging**
